Songify/Songify/config/routes.rb
Rails.application.routes.draw do
  get 'valuations/update'
  post 'valuations/update'
  get 'valuations/create'
  post 'valuations/create'
  resources :concerts
  get 'favorites/update'
  post 'favorites/update'
  get 'artists/star'
  post 'artists/star'

  resources :music_events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'static_pages#homepage'

  devise_for :users , controllers: {
    session: 'users/sessions',
    registration: 'users/registrations',
    omniauth: 'users/omniauth',
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: 'users/confirmations'}
  get 'users/index' => 'users#index', as: "users_index"
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  get 'sign_in' => "sessions#new" # custom path to login/sign_in
  get 'sign_up' => "registrations#new", as: "new_user_registration_path" # custom path to sign_up/registration
  # rotte _header
  get 'homepage'       => 'static_pages#homepage'  #rotta homepage
  get 'artists'        => 'artists#index'   #rotta artisti
  get 'tweet'         => 'tweet#index'    #rotta tweets
  get 'chatroom'       => 'static_pages#chatroom'  #rotta chatroom
  # rotte _footer
  get 'about'          => 'static_pages#about'     #rotta informazioni
  get 'contact'        => 'static_pages#contact'   #rotta contatti

  mount ActionCable.server => '/cable'


  resources :tweets, :concerts, :artists, :comments, :valuations, :reports
  resources :artists do
    post :rank
    patch :rank
    put :rank
    get :rank
  end
  resources :artists do
    post :star
    patch :star
    put :star
    get :star
  end
  resources :reports do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :comments do
    member do
      put "like" => "comments#like"
    end
  end
  resources :comments do
    member do
      put "dislike" => "comments#dislike"
    end
  end
  resources :comments do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :comments do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :concerts do
    patch :index2
    put :index2
    get :index2
  end
  resources :concerts do
    patch :search
    put :search
    get :search
  end
  resources :concerts do
    patch :searchDate
    put :searchDate
    get :searchDate
  end
  resources :concerts do
    patch :searchZone
    put :searchZone
    get :searchZone
  end
  resources :concerts do
    patch :search_id
    put :search_id
    get :search_id
  end
   resources :users do
    patch :removeFavorite
    put :removeFavorite
    get :removeFavorite
  end
  resources :users do
    patch :addFavorite
    put :addFavorite
    get :addFavorite
  end

  resources :users do
    patch :ban
    put :ban
  end
  resources :users do
    patch :mod
    put :mod
  end
  resources :users do
    patch :admin
    put :admin
  end
  resources :users do
    patch :show_user
    put :show_user
    get :show_user
  end
  resources :users, :only =>[:show, :index, :edit, :update, :ban, :unban, :favorites]
end

Songify/Songify/app/models/concert.rb
class Concert < ApplicationRecord
end

Songify/Songify/app/controllers/concerts_controller.rb
require 'location'
require 'lastfm'
class ConcertsController < ApplicationController
    before_action :require_login

    def require_login
      unless current_user != nil
      flash[:error] =  "You require to login!"
        redirect_to new_user_session_path # halts request cycle
      end
    end

    remote = Songkickr::Remote.new ENV["SONGKICK_API_KEY"]
    @@results = remote.events(location: "clientip").results

    def index2
        @results = @@results
    end

    def index
        @results = @@results
    end

    def search
        @results = @@results
        @artists = show_top_artists
        @input = params[:search]
    end

    def searchDate
        @results = @@results
        @date = params[:date]
    end

    def searchZone
        @results = @@results
        @zone = params[:zone]
    end

    def show
        @events = @@results
        @event = search_id(@events, params[:id])
        my_loc = BingLocator.new()
        my_loc.api_key = 'AjCnyg3J-cQx0PfxOJd8GD_XYZqqba8-tNAem7JgPVd_LN0H-DY_TlwDzYktf4lt'
        @venue = get_venue_by_id(@event.venue.id)
        if(@event.venue.lat == nil && @event.venue.lat == nil)
            my_loc.query = @venue.metro_area.display_name
            @location = my_loc.get_img_url_by_query(600,300)
        else 
            my_loc.latitude = @event.venue.lat 
            my_loc.longitude = @event.venue.lng
            @location = my_loc.get_img_url_by_point(600,300)
           
        end
        my_loc.zoom_level = '16'
        @bio = get_artist_bio('')
    end

    private
    def search_id(results, id)
        results.each do |event|
            if(event.id ==  id.to_i)
                return event
            end
        end
        render_not_found
    end

    private
    def render_not_found
        render :file => "#{Rails.root}/public/404.html",  :status => 404
    end

    private
    def get_venue_by_id(id)
        remote = Songkickr::Remote.new ENV["SONGKICK_API_KEY"]
        @venue = remote.venue(id)
        return @venue
    end

    private
    def show_top_artists
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        return lastfm.chart.get_top_artists
    end

     private
     def get_artist_bio(artist)
         lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
         token = lastfm.auth.get_token
         lastfm.session = lastfm.auth.get_session(token: token)['key']

         return lastfm.artist.getInfo(artist: artist)
     end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:name, :id, :venue)
    end
end

Songify/Songify/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Songify/Songify/app/views/concerts/_form.html.erb
<%= form_with(model: concert, local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_field :venue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Songify/Songify/app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

Songify/Songify/app/views/concerts/index.html.erb
<!--
<div class="container message" style="color: gray;" >
    <h4 ><%= form_tag concert_search_path(concert_id: current_user), :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
    <% end %>
    </h4>
  </div>

<div class="container message" style="color: gray;" >
    <h4 ><%= form_tag concert_searchDate_path(concert_id: current_user), :method => 'get' do %>
      <%= date_field_tag :date, params[:date] %>
      <%= submit_tag "Search date" %>
    <% end %>
    </h4>
</div>
-->
<div class="container message" style="color: gray;">
  <h3>Upcoming Concerts</h3>
  <p>choose your favorite or discover according to the area</p>
  <br/>
  <h4><div>
    <%= form_tag concert_searchZone_path(concert_id: current_user), :method => 'get' do %>
      <div class="input-group">
        <%= select_tag "zone", raw("<option>Roma nord</option><option>Roma ovest</option><option>Roma est</option><option>Roma sud</option>"), class: 'form-control', style: "color: gray; left: 24.5%; width: 48.5%; height: 20%; border-color: black" %>
        <div class="input-group-btn">
            <button class="btn btn-default" style="left: -290px; background-color: rgba(255,255,255,0.65); border: none;" type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <br/>
</div>

<div class="list-group">
    <% @results.each do |result| %>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= concert_path(result.id) %>>
            <div>
                <strong style="color: black"><%= result.display_name %></strong>
                <br>
                <%= @xx %>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light"><%= result.type %></span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
    <% end %>
</div>

Songify/Songify/app/views/concerts/index2.html.erb
<div class="container message" style="color: gray;">
  <h3>Your favorites'</h3>
  <br/>
</div>
<div class="list-group">
    <% @results.each do |result| %>
        <% if current_user.favorites.split(' ').include?(result.id.to_s) %>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= concert_path(result.id) %>>
            <div>
                <strong style="color: black"><%= result.display_name %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light"><%= result.type %></span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
        <%end%>
    <% end %>
</div>

Songify/Songify/app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Back', concerts_path %>

Songify/Songify/app/views/concerts/search.html.erb
<div class="container message" style="color: gray;">
  <h3>Results</h3>
  <h4>You searched for this events</h4>
  <br/>
</div>
<% @index = 0 %>
<% @results.each do |result| %>
  <% @xx = ''%>
      <% result.performances.each do |cc|%>
      <% @xx = cc.display_name.to_s.downcase.include?(@input.to_s.downcase) %>
      <% end %>
      <% if result.display_name.downcase.include?(@input.to_s.downcase) || result.id.to_s.include?(@input.to_s) || result.location.city.downcase.to_s.include?(@input.to_s.downcase) || result.venue.display_name.to_s.downcase.include?(@input.to_s.downcase) || @xx %>
      <% @index = 1 %>
      <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= concert_path(result.id) %>>
          <div>
              <strong style="color: black"><%= result.display_name %></strong>
              <br>
              <br>
              <span style="background-color: darksalmon;" class="badge badge-light"><%= result.type %></span>
              <span class="pull-right" style="margin-top: -3%;">
                  <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
              </span>
          </div>
      </a>
      <%end%>
<% end %>
<%if @index == 0 %>
<div class="container message" style="color: gray;">
  <h4>No results found.</h4>
</div>
<br/>
<%end%>

<% @index = 0 %>

<div class="container message" style="color: gray;">
  <h4>You searched for this artists</h4>
  <br/>
</div>
<% @artists.each do |artist| %>
    <% if artist['name'].to_s.downcase.include?(@input.to_s.downcase) %>
    <% @index = 1 %>
    <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= artist_path(artist['name'])%>>
        <div>
            <strong style="color: black;"><%= artist['name'] %></strong>
            <br>
            <br>
            <span class="pull-right" style="margin-top: -3%;">
                <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            </span>
            <br/>
        </div>
    </a>
    <%end%>
<% end %>

<%if @index == 0 %>
<div class="container message" style="color: gray;">
  <h4>No results found.</h4>
</div>
<br/>
<%end%>

<%@index = 0 %>
<div class="container message" style="color: gray;">
  <h4>Artists inherent to: #<%=@input.to_s%></h4>
  <br/>
</div>
<% @artists.each do |artist| %>
    <% if ArtistsController.get_tags(artist['name']).map{|x| x['name'].downcase}.include?(@input.to_s.downcase) %>
    <% @index = 1 %>
    <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= artist_path(artist['name'])%>>
        <div>
            <strong style="color: black;"><%= artist['name'] %></strong>
            <br>
            <br>
            <span class="pull-right" style="margin-top: -3%;">
                <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            </span>
            <br/>
        </div>
    </a>
    <%end%>
<% end %>
<% if @index == 0%>
<div class="container message" style="color: gray;">
  <h4>No results found.</h4>
</div>
<br/>
<% end %>


</div>

Songify/Songify/app/views/concerts/searchDate.html.erb
<div class="container message" style="color: gray;">
  <h3>Results</h3>
  <h4>You searched for this events</h4>
  <br/>
</div>

<div class="list-group">
    <% @results.each do |result| %>
        <% if result.start.to_s.first(10) == @date.to_s %>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= concert_path(result.id) %>>
            <div>
                <strong style="color: black"><%= result.display_name %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light"><%= result.type %></span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
        <%end%>
    <% end %>
</div>

Songify/Songify/app/views/concerts/searchZone.html.erb
<div class="container message" style="color: gray;">
  <h3>Results</h3>
  <h4>You searched for this events in zone: <%=@zone%></h4>
  <br/>
</div>

<div class="list-group">
    <% @bool = false %>
    <% @results.each do |result| %>
        <% if @zone.to_s=="Roma nord" %>
            <% if result.venue.lat.to_f>=41.9109 %><% @bool = true %><% end %><%end%>
        <% if @zone.to_s=="Roma sud" %>
            <% if result.venue.lat.to_f<41.9109 %><% @bool = true %><% end %><%end%>
        <% if @zone.to_s=="Roma ovest" %>
            <% if result.venue.lng.to_f<=12.4818 %><% @bool = true %><% end %><%end%>
        <% if @zone.to_s=="Roma est" %>
            <% if result.venue.lng.to_f>12.4818 %><% @bool = true %><% end %><%end%>
        <% if @bool == true%>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= concert_path(result.id) %>>
            <div>
                <strong style="color: black"><%= result.display_name %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light"><%= result.type %></span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
        <%end%>
    <% end %>
</div>

Songify/Songify/app/views/concerts/show.html.erb
<h3 style="color: gray;"><strong><%= @event.type %></strong></h3>
<% @event.performances.each do |performance| %>
  <blockquote>
      <p style="color: gray;">Artist: <strong><%= link_to performance.display_name %></strong></p>
      <p style="color: gray;">Date: <strong><%= @event.start.to_formatted_s(:long) %></strong></p> <small><cite> <%= @event.venue.display_name %> - <%= @event.venue.metro_area.display_name %> <i class="glyphicon glyphicon-map-marker"></i></cite></small>
  </blockquote>
  <div class="row" style="margin-left: inherit; margin-top: 40px; margin-bottom: 40px">
    <% @imgj = "https://images.sk-static.com/images/media/profile_images/artists/" + performance.artist.id.to_s + "/huge_avatar" %>
    <img style="border-radius: 6px;" src = "<%= @imgj %>" alt="No image" />
  </div>
<% end %>
<div style="margin-bottom: 5%">
  <% if current_user.favorites != nil && current_user.favorites.split(' ').include?(@event.id.to_s) %>
	  	<% if @event.type == "Concert"%>
	      <h5 style="color: gray;"><strong><%= link_to "Unfavorite", user_removeFavorite_path(id: @event.id,user_id: current_user.id) %> this concert, share</strong></h5>
	  	<%else%>
	      <h5 style="color: gray;"><strong><%= link_to "Unavorite", user_removeFavorite_path(id: @event.id,user_id: current_user.id) %> this festival, share</strong></h5>
	  	<% end %>

  <%else%>

	  <% if @event.type == "Concert"%>
	      <h5 style="color: gray;"><strong>Put in yours <%= link_to "favorite", user_addFavorite_path(id: @event.id,user_id: current_user.id) %> and share this concert</strong></h5>
	  <%else%>
	      <h5 style="color: gray;"><strong>Put in yours <%= link_to "favorite", user_addFavorite_path(id: @event.id,user_id: current_user.id) %> and share this festival</strong></h5>
	  <% end %>
  <% end %>

  <p class="btn-social btn-twitter">
    <% @mes = "https://twitter.com/intent/tweet?url=" + @event.uri %>
      <%= link_to @mes, class: "btn btn-primary" do %><i class="fa fa-twitter"></i> on Twitter
    <% end %>
  </p>
  <div class="row" style="margin-left: inherit; margin-top: 5%; color: gray;">
    <%= image_tag @location , alt: "Map", style: "border-radius: 6px 6px 6px 6px;" %>
    <p style="margin-left: 20px;">
      <strong><%= @venue.display_name %></strong><br/>
      <%= @venue.street %><br/>
      <%= @venue.zip %> - <%= @venue.metro_area.display_name %><br/><br/>
      look the <%= link_to "link", @venue.website %> for more information on the local<br/>
      <%= @venue.phone %><br/>
    </p>
  </div>
</div>