Songify/Songify/config/routes.rb
Rails.application.routes.draw do
  get 'valuations/update'
  post 'valuations/update'
  get 'valuations/create'
  post 'valuations/create'
  resources :concerts
  get 'favorites/update'
  post 'favorites/update'
  get 'artists/star'
  post 'artists/star'

  resources :music_events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'static_pages#homepage'

  devise_for :users , controllers: {
    session: 'users/sessions',
    registration: 'users/registrations',
    omniauth: 'users/omniauth',
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: 'users/confirmations'}
  get 'users/index' => 'users#index', as: "users_index"
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  get 'sign_in' => "sessions#new" # custom path to login/sign_in
  get 'sign_up' => "registrations#new", as: "new_user_registration_path" # custom path to sign_up/registration
  # rotte _header
  get 'homepage'       => 'static_pages#homepage'  #rotta homepage
  get 'artists'        => 'artists#index'   #rotta artisti
  get 'tweet'         => 'tweet#index'    #rotta tweets
  get 'chatroom'       => 'static_pages#chatroom'  #rotta chatroom
  # rotte _footer
  get 'about'          => 'static_pages#about'     #rotta informazioni
  get 'contact'        => 'static_pages#contact'   #rotta contatti

  mount ActionCable.server => '/cable'


  resources :tweets, :concerts, :artists, :comments, :valuations, :reports
  resources :artists do
    post :rank
    patch :rank
    put :rank
    get :rank
  end
  resources :artists do
    post :star
    patch :star
    put :star
    get :star
  end
  resources :reports do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :comments do
    member do
      put "like" => "comments#like"
    end
  end
  resources :comments do
    member do
      put "dislike" => "comments#dislike"
    end
  end
  resources :comments do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :comments do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :concerts do
    patch :index2
    put :index2
    get :index2
  end
  resources :concerts do
    patch :search
    put :search
    get :search
  end
  resources :concerts do
    patch :searchDate
    put :searchDate
    get :searchDate
  end
  resources :concerts do
    patch :searchZone
    put :searchZone
    get :searchZone
  end
  resources :concerts do
    patch :search_id
    put :search_id
    get :search_id
  end
   resources :users do
    patch :removeFavorite
    put :removeFavorite
    get :removeFavorite
  end
  resources :users do
    patch :addFavorite
    put :addFavorite
    get :addFavorite
  end

  resources :users do
    patch :ban
    put :ban
  end
  resources :users do
    patch :mod
    put :mod
  end
  resources :users do
    patch :admin
    put :admin
  end
  resources :users do
    patch :show_user
    put :show_user
    get :show_user
  end
  resources :users, :only =>[:show, :index, :edit, :update, :ban, :unban, :favorites]
end

Songify/Songify/app/controllers/artists_controller.rb
require 'lastfm'
require 'httparty'

class ArtistsController < ApplicationController
    before_action :require_login
     respond_to :js, :json, :html


    def require_login
      unless current_user != nil
      flash[:error] =  "You require to login!"
        redirect_to new_user_session_path # halts request cycle
      end
    end

    def index
        @topArtists = show_top_artists
    end

    def star
        @topArtists = show_top_artists
        @star = params[:stars]
    end

    def rank
        @revec=''
        @arvec=''
        @topArtists = show_top_artists
        @topArtists.each do |artist|
            @arvec << artist['name']+'+'
            @revec << ArtistsController.get_avg(artist['name']).to_s+' '
        end
        @c = @revec.split(' ').zip(@arvec.split('+')).sort.reverse
    end

    def show
        @artists = show_top_artists
        @artist = get_artist_by_name(@artists,params[:id])
        @name = params[:id]
        @bio = get_artist_bio(params[:id])
        @id = get_id_by_name(params[:id])
        @topAlbums = get_top_albums_by_artist_name(params[:id])
        @topTracks = get_top_tracks_by_artist_name(params[:id])
        @similarArtists = get_similar_artists(params[:id])
        @tags = ArtistsController.get_tags(params[:id])
        @comments =Comment.all
        @val = Valuation.all
    end

public

def self.get_avg(name)
        @sum = 0.0
            @n = 0.0
            @val = Valuation.all
            @val.each do |val|
                if(val.artist ==  name)
                    @sum =@sum + val.value.to_f
                    @n=@n+1
                end
            end
            if @sum != 0.0
                @sum = @sum/@n
            end
            if @sum == 'NaN'
                return 0.to_i
            else
                return @sum
            end
    end

    def self.has_reviewed(user,name)
        @val = Valuation.all
        @val.each do |val|
            if val.user_id.to_i == user && val.artist.to_s == name
                return val
            end
        end
        return Valuation.new
    end

    def self.has_reported_comment(user,comment)
    @rep = Report.all
    @rep.each do |r|
      if r.user_id.to_i == user.to_i && r.comment.id.to_i == comment.to_i && !r.verif
        return true
      end
    end
    return false
end

   def self.has_reported_user(user,us)
    @rep = Report.all
    @rep.each do |r|
      if r.user_id.to_i == user.to_i && r.ut.to_i == us.to_i && r.verif
        return true
      end
    end
    return false
end
    def show_top_artists
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        return lastfm.chart.get_top_artists
    end

    private
    def get_artist_bio(name)
         lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
         token = lastfm.auth.get_token
         bio =  lastfm.artist.get_info(artist: name)
         return bio
    end

    private
    def get_artist_by_name(artists,name)
        artists.each do |artist|
            if(name == artist['name'])
                return artist
            end
        end
        render_not_found
    end

    private
    def get_id_by_name(name)
        response = HTTParty.get('https://api.songkick.com/api/3.0/search/artists.json?apikey='+ ENV['SONGKICK_API_KEY'] + '&query='+name+'')
        @resultsPage = JSON.parse(response.body)
        return @resultsPage["resultsPage"]["results"]["artist"][0]["id"]
    end

    private
    def get_top_albums_by_artist_name(name)
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        albums = lastfm.artist.get_top_albums(artist: name)
    end

    private
    def get_top_tracks_by_artist_name(name)
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        tracks = lastfm.artist.get_top_tracks(artist: name)
    end

    private
    def get_similar_artists(name)
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        tracks = lastfm.artist.get_similar(artist: name)
    end

    private
    def self.get_tags(name)
        lastfm = Lastfm.new(ENV["LASTFM_API_KEY"], ENV["LASTFM_API_SECRET"])
        token = lastfm.auth.get_token
        tracks = lastfm.artist.get_top_tags(artist: name)
    end

    private
    def render_not_found
        render :file => "#{Rails.root}/public/404.html",  :status => 404
    end


end

Songify/Songify/app/helpers/artists_helper.rb
module ArtistsHelper
end

Songify/Songify/app/views/artists/index.html.erb
<div class="container message" style="color: gray;">
  <h3>Top Artists</h3>
  <p><%= link_to "view", artist_rank_path(artist_id: 0) %> the first artists on Songify</p>
  <br/>
  <h4><div>
    <%= form_tag artists_star_path, local: true do %>
      <div class="input-group">
        <%= number_field_tag :stars, params[:stars], in: 0..5, class: 'form-control', placeholder: "Search based on ranking", style: "left: 24.5%; width: 48.5%; height: 20%; border-color: black" %>
        <div class="input-group-btn">
            <button class="btn btn-default" style="left: -290px; background-color: rgba(255,255,255,0.65); border: none;" type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <br/>
</div>

<div class="list-group">
    <% @topArtists.each do |artist| %>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= artist_path(artist['name'])%>>
            <div>
                <strong style="color: black;"><%= artist['name'] %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light">
                  <%= @avg = ArtistsController.get_avg(artist['name']) %> <i class="fa fa-star"></i>
                </span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
    <% end %>
</div>

Songify/Songify/app/views/artists/rank.html.erb
<div class="container message" style="color: gray;">
  <h3>Rank Artists</h3>
  <p>the 50 artists of the moment</p>
  <br/>
</div>

<div class="list-group">
    <% n=1 %>
    <% @c.each do |record| %>
    <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= artist_path(record[1])%>>
            <div>
                <strong style="color: black;"><%= "#"+n.to_s+"  " %><%= record[1] %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light">
                  Average: <%= record[0]%>
                  <% n = n+1 %>
                </span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        <% end %>
    </a>
</div>

Songify/Songify/app/views/artists/show.html.erb
<%= @albums %>
<h3><strong><%= link_to @artist['name'], @artist['url'] %>  <%= @avg %></strong></h3>
  <blockquote>
      <p style="color: gray;"><i class='fa fa-chevron-circle-right' title="playcount."></i> <%= @artist['playcount'] %></p>
      <p style="color: gray;"><i class='fa fa-microphone' title="listeners."></i> <%= @artist['listeners'] %></p>
  </blockquote>
  <div style="margin-left: inherit; margin-bottom: 4%; color: gray">
    <% @imgar = "https://images.sk-static.com/images/media/profile_images/artists/" + @id.to_s + "/huge_avatar" %>
    <img style="border-radius: 6px; float:left; margin-right: 25px; margin-bottom: 20px;" src = "<%= @imgar %>" alt="No image" />
    <div style="text-align: justify;">
      <h3 style="margin-top: inherit; color: darksalmon;">Biography</h3>
      <%= @bio['bio']['content'].html_safe %>
    </div>
  </div>

  <h3 style="color: darksalmon;"><%= @artist['name'] %>'albums</h3>
  <div class="container-fluid">
    <div style="width: 100%; height: 170px; overflow-x: scroll;">
        <% @topAlbums.each do |album| %>
          <% @imgal = album['image'][2]['content'] %>
          <% @tital = album['name']%>
            <div class="row float-left">
              <img class="img-fluid" style="weight: 160px; height: 160px; margin-left: 40px; margin-bottom: 5%; border-radius: 2px;" title= "<%= @tital %>." src= "<%= @imgal %>"></img>
            </div>
        <% end %>
    </div>
  </div>
  <br/>

  <h3 style="text-align: justify; color: darksalmon;">
    <cite><h4>TAGs <h4/>
      <% @tags.each do |tag| %>
        <% @href = tag["url"] %>
        <button type="button" onclick="window.open('<%= @href %>','blank');" class="btn btn-outline-secondary"><%= tag["name"] %></button>
      <% end %>
    </cite>
  </h3>
  <br/>

  <h3 style="color: darksalmon; margin-bottom: 1%;">Post a rating</h3>
  <h4><div>
    <% @v =ArtistsController.has_reviewed(current_user.id.to_i,@artist['name'].to_s) %>
    <% if @v.value == 0 %>
    <%= @v.artist %>
    <%= form_tag valuations_create_path(user_id:current_user.id,artist: @name, value: @value, valuation_id: current_user.id), local: true do %>
      <div class="input-group">
          <%= number_field_tag :value, params[:value], in: 1..5, placeholder: "Review here!", class: 'form-control', style: "height: 34px; border-color: black; color: black; background-color: rgba(255,255,255,0.65);" %>
          <div class="input-group-btn">
            <button class="btn btn-default" style="background-color: gray; border: none;" type="submit">Commit review</button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <%else%>
  <h4><div>
    <%= form_tag valuations_update_path(user_id:current_user.id,artist: @name, value: @value, valuation_id: @v.id, id:@v.id), local: true do %>
      <div class="input-group">
          <%= number_field_tag :value, params[:value], in: 1..5, value:@v.value, placeholder: "Edit here!", class: 'form-control', style: "height: 34px; border-color: black; color: black; background-color: rgba(255,255,255,0.65);" %>
          <div class="input-group-btn">
            <button class="btn btn-default" style="background-color: gray; border: none;" type="submit">Edit review</button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <% end %>

  <h3 style="color: darksalmon; margin-bottom: 1%;">Post a comment</h3>
  <h4><div>
    <%= form_tag comment_create_path(user_id: current_user.id, comment_id:'1', artist: @name), local: true do %>
      <div class="input-group">
          <%= text_area_tag :body, params[:body], placeholder: "Write here!", class: 'form-control', style: "height: 33px; border-color: black; color: black; background-color: rgba(255,255,255,0.65);" %>
          <div class="input-group-btn">
            <button class="btn btn-default" style="background-color: gray; border: none;" type="submit">Commit review</button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <br/>

  <div class="container message" style="color: gray;" >
      <% @comments.each do |comment| %>
        <% if comment.artist == @artist['name'] %>
          <% if comment.user_id.to_i != current_user.id.to_i %>
          <% @us = User.find(comment.user_id) %>
        <h5>
          <%if @us.id.to_s != current_user.id.to_s %>
          <%= link_to @us.username, user_show_user_path(@us) %>
          <%else%>
            <%= link_to "You", user_path %>
            <%= form_tag comment_update_path(user_id: current_user.id, comment_id:comment.id, artist: @name, id:comment.id), local: true do %>
              <%= text_field_tag :body, params[:body], value:comment.body  %>
              <%= submit_tag "Edit" %>
            <%end%>
          <%end%>
        </h5>
        <h4><%= comment.body %></h4>
        <h5>
          <%= link_to like_comment_path(comment.id), class:"like-btn", method: :put, remote: :true do%>
            <i class="fa fa-thumbs-up fa" style="margin-left: 1%;"></i>
            <span class="likes-count"><%= comment.get_upvotes.size %> </span>
          <%end%>
          <%= link_to dislike_comment_path(comment.id), class:"unlike-btn", method: :put, remote: :true do%>
          <i class="fa fa-thumbs-down fa" style="margin-left: 1%;"></i>
          <span class="likes-count" style="margin-right: 1%;"><%= comment.get_downvotes.size %></span>
          <%end%>
        </h5>
        <h5>
          <% if ArtistsController.has_reported_comment(current_user.id, comment.id) == true %>
            You've reported this comment!
          <%else%>
            <%= link_to "Report comment", report_create_path(user_id:current_user.id, comment:comment, ut:comment.user_id, artist: @name, report_id:0, verif:false) %>
          <%end%>
          <% if ArtistsController.has_reported_user(current_user.id, comment.user_id) == true %>
            You've reported this user!
          <%else%>
            <%= link_to "Report user", report_create_path(user_id:current_user.id, comment:comment, ut:comment.user_id, artist: @name, report_id:0, verif:true), style:"margin-left: 1%;" %>
          <%end%>
        <%end%>
        </h5>
        <h5 style="margin-bottom: 50px;">
            <% if current_user.admin? || current_user.mod? || current_user.id == comment.user_id%>
            <%= link_to "Remove comment", comment, method: :delete , data: { confirm: "You sure?" }, style: "color: white;" %>
            <% end %>
        </h5>
        <%end%>
        <%end%>
  </div>

Songify/Songify/app/views/artists/show.js.erb
$("#button").click(function() {
  $("#fn").show();
});

Songify/Songify/app/views/artists/star.html.erb
<div class="container message" style="color: gray;">
  <h3>Results</h3>
  <h4>You searched for this stars</h4>
  <br/>
  <h4><div>
    <%= form_tag artists_star_path, local: true do %>
      <div class="input-group">
        <%= number_field_tag :stars, params[:stars], in: 0..5, class: 'form-control', placeholder: "Search", style: "left: 24.5%; width: 48.5%; border-color: black" %>
        <div class="input-group-btn">
            <button class="btn btn-default" style="left: -290px; background-color: rgba(255,255,255,0.65); border: none;" type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
      </div>
    <% end %>
  <div/></h4>
  <br/>
</div>

<div class="list-group">
    <% @topArtists.each do |artist| %>
        <% if ArtistsController.get_avg(artist['name']).to_f >= @star.to_f && ArtistsController.get_avg(artist['name']) < @star.to_f+1.0 %>
        <a class="list-group-item clearfix" style="border-style: none; margin-bottom: 2%; width: 50%; left: 25%; border-radius: 6px; background-color: rgba(255,255,255,0.65);" href= <%= artist_path(artist['name'])%>>
            <div>
                <strong style="color: black;"><%= artist['name'] %></strong>
                <br>
                <br>
                <span style="background-color: darksalmon;" class="badge badge-light">
                  <%= @avg = ArtistsController.get_avg(artist['name']) %> <i class="fa fa-star"></i>
                </span>
                <span class="pull-right" style="margin-top: -3%;">
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </span>
            </div>
        </a>
        <% end %>
    <% end %>
</div>

Songify/Songify/app/views/artists/vote.js.erb
<% if current_user.liked? comment %>
	$('.like-btn').addClass('liked');
<% else %>
	$('.like-btn').addClass('like-btn');
<%end%>
$('.likes-count').html("<%=comment.get_upvotes.size %>")

<% if current_user.disliked? comment %>
	$('.dislike-btn').addClass('disliked');
<% else %>
	$('.dislike-btn').addClass('dislike-btn');
<%end%>
$('.dislikes-count').html("<%=comment.get_downvotes.size %>")