Songify/Songify/config/routes.rb
Rails.application.routes.draw do
  get 'valuations/update'
  post 'valuations/update'
  get 'valuations/create'
  post 'valuations/create'
  resources :concerts
  get 'favorites/update'
  post 'favorites/update'
  get 'artists/star'
  post 'artists/star'

  resources :music_events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root  'static_pages#homepage'

  devise_for :users , controllers: {
    session: 'users/sessions',
    registration: 'users/registrations',
    omniauth: 'users/omniauth',
    omniauth_callbacks: "users/omniauth_callbacks",
    confirmations: 'users/confirmations'}
  get 'users/index' => 'users#index', as: "users_index"
  get 'edit' => 'users#edit'
  post 'edit' => 'users#update'
  get 'sign_in' => "sessions#new" # custom path to login/sign_in
  get 'sign_up' => "registrations#new", as: "new_user_registration_path" # custom path to sign_up/registration
  # rotte _header
  get 'homepage'       => 'static_pages#homepage'  #rotta homepage
  get 'artists'        => 'artists#index'   #rotta artisti
  get 'tweet'         => 'tweet#index'    #rotta tweets
  get 'chatroom'       => 'static_pages#chatroom'  #rotta chatroom
  # rotte _footer
  get 'about'          => 'static_pages#about'     #rotta informazioni
  get 'contact'        => 'static_pages#contact'   #rotta contatti

  mount ActionCable.server => '/cable'


  resources :tweets, :concerts, :artists, :comments, :valuations, :reports
  resources :artists do
    post :rank
    patch :rank
    put :rank
    get :rank
  end
  resources :artists do
    post :star
    patch :star
    put :star
    get :star
  end
  resources :reports do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :valuations do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :comments do
    member do
      put "like" => "comments#like"
    end
  end
  resources :comments do
    member do
      put "dislike" => "comments#dislike"
    end
  end
  resources :comments do
    post :create
    patch :create
    put :create
    get :create
  end
  resources :comments do
    post :update
    patch :update
    put :update
    get :update
  end
  resources :concerts do
    patch :index2
    put :index2
    get :index2
  end
  resources :concerts do
    patch :search
    put :search
    get :search
  end
  resources :concerts do
    patch :searchDate
    put :searchDate
    get :searchDate
  end
  resources :concerts do
    patch :searchZone
    put :searchZone
    get :searchZone
  end
  resources :concerts do
    patch :search_id
    put :search_id
    get :search_id
  end
   resources :users do
    patch :removeFavorite
    put :removeFavorite
    get :removeFavorite
  end
  resources :users do
    patch :addFavorite
    put :addFavorite
    get :addFavorite
  end

  resources :users do
    patch :ban
    put :ban
  end
  resources :users do
    patch :mod
    put :mod
  end
  resources :users do
    patch :admin
    put :admin
  end
  resources :users do
    patch :show_user
    put :show_user
    get :show_user
  end
  resources :users, :only =>[:show, :index, :edit, :update, :ban, :unban, :favorites]
end

Songify/Songify/app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :valuations, dependent: :destroy
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable,
         :omniauthable, omniauth_providers: [:twitter]

  #attr_accessor :email, :password, :remember_me, :avatar, :avatar_cache, :remove_avatar

#  enum gender: {undisclosed: 0, female:1, male:2, other:3}
  validates_presence_of   :username
  validates_integrity_of  :avatar
  validates_processing_of :avatar
  def profile_image_uri(size = :mini)
  parse_encoded_uri(insecure_uri(profile_image_uri_https(size))) unless @attrs[:profile_image_url_https].nil?
  end

  def self.create_from_provider_data(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.nickname
      user.first_name  = auth.info.name              # assuming the user model has a name
      user.email = auth.info.email            # since we are using twitter, which hasn't got any email, we'll just comment this
      user.password = 123456
      user.provider = auth.provider
      user.profile_image_url = auth[:extra][:raw_info][:profile_image_url]
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
    #redirect_to concerts_path, alert: "Thank you."
  end

  def email_required?
    super && provider.blank?
  end

  def active_for_authentication? 
    super && !ban? 
  end 
  
  def inactive_message 
    !ban? ? super : :not_ban
  end
end

Songify/Songify/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
   def new
     super
   end

  # POST /resource/confirmation
   def create
     super
   end

  # GET /resource/confirmation?confirmation_token=abcdef
   def show
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?

    if resource.errors.empty?
      set_flash_message!(:notice, :confirmed)
      respond_with_navigational(resource){ redirect_to user_path(resource) }
    else
      respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
    end
   end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
   def after_confirmation_path_for(resource_name, resource)
    redirect_to user_path(resource)
   end
end

Songify/Songify/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def twitter
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      flash[:error] = 'There was a problem signing you in through Twitter. Please register or try signing in later.'
      redirect_to new_user_registration_url
    end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    super
  end

=begin def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
=end

  # GET|POST /users/auth/twitter/callback
  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end

  # protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    super(scope)
  end
end

Songify/Songify/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :authenticate_user!
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
   super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
   def update
     super
   end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

Songify/Songify/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

# /resource/sign_up
   def new
     super
    UserMailer.welcome_email(self).deliver_now
   end

  # POST /resource
   def create
    super
  end

  # GET /resource/edit
  def edit
     super
   end

  # PUT /resource
   def update
     self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

   if resource.update_with_password(params[resource_name])
     set_flash_message :notice, :updated if is_navigational_format?
     sign_in resource_name, resource, :bypass => true
     respond_with resource, :location => after_update_path_for(resource)
   else
     clean_up_passwords(resource)
     respond_with_navigational(resource){ render_with_scope :edit }
   end
  end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
 

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  # Notice the name of the method
  def sign_up_params
    params.require(:user).permit(:name, :email, :gender, :location, :password, :password_confirmation)
  end
end

Songify/Songify/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
      super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

Songify/Songify/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
     super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
     super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
     super(resource)
  end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Songify/Songify/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :verify_authenticity_token


  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def show_user
    @user = User.find(params[:user_id])
  end
  def edit
      @user.avatar.attach(params[:avatar])
  end

  def destroy
    @user = User.find(params[:id]) 
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

   def update
 @user = User.find(params[:id])
 if @user.update_attributes(secure_params)
  redirect_to users_path, :notice => "User updated."
 else
  redirect_to users_path, :alert => "Unable to update user."
 end
end
 public
 def ban
    @user = User.find(params[:user_id])
    if @user.ban?
      @user.update_attribute(:ban, false)
      redirect_to users_path, :notice => "User unbanned."
    else
      @user.update_attribute(:ban, true)
      ReportsController.destroy_ut(@user.id)
      redirect_to users_path, :notice => "User banned."

    end	
end

  def mod
    @user = User.find(params[:user_id])
    if @user.mod?
      @user.update_attribute(:mod, false)
      redirect_to users_path, :notice => "User unmoded."
    else
      @user.update_attribute(:mod, true)
      redirect_to users_path, :notice => "User moded."
    end 
  end

  def admin
    @user = User.find(params[:user_id])
    if @user.admin?
      @user.update_attribute(:admin, false)
      redirect_to users_path, :notice => "User unadmined."
    else
      @user.update_attribute(:admin, true)
      redirect_to users_path, :notice => "User admined."
    end 
  end

  def addFavorite
    user = params[:user_id]
    event = params[:id]
    @user = User.find(user)
    if @user.favorites != nil
      @user.favorites << event 
    else
    @user.update_attribute(:favorites, event)
    end
    @user.favorites << + ' '
      @user.save
    redirect_to concert_path(id: event), :notice => "User favorited."
  end

  def removeFavorite
    @fav = current_user.favorites.split(' ')
    @event = params[:id]
    @i = 0
    for conc in @fav do
      if conc == @event.to_s
        @fav[@i] = ""
      end
       @i = @i+1
    end
    @fav = @fav.join(' ')
    @fav += " "
    current_user.update_attribute(:favorites, @fav)
    redirect_to concert_path(id: @event), :notice => "User unfavorited."
  end
end

Songify/Songify/app/helpers/users_helper.rb
module UsersHelper

  end

Songify/Songify/app/views/users/index.html.erb
<div class="container message">
  <h3 style="color: gray;">Administers Songify's users</h3>
  <p style="color: white;"><% @reps = Report.all %>
      <% @reps.each do |report| %>
          <% @us = User.find(report.user_id) %>
          <% @u = User.find(report.ut.to_i) %>

          <%= @us.username%> just reported
          <% if report.verif == false%> the comment: <% @c = report.comment %><%= @c.body %> of <% end %>
          <%=link_to @u.username, user_show_user_path(@u) %>
          <% if report.verif == false%> <%= link_to "Remove comment", @c, method: :delete , data: { confirm: "You sure?" }, style: "color: white;" %>
          <%end%>
          <%= link_to 'Ban user', user_ban_path(@u), method: :put, data: { confirm: 'This user will be banned. Proceed?' } %>
          <%= link_to 'Delete user', @u, method: :delete, data: { confirm: "This user will be deleted. Proceed?" } %>
          <br>
      <%end%>
  </p>
  <br/>
</div>

<div class="row">
    <div class="col-lg-4">
        <% if current_user && (current_user.admin? || current_user.mod?) %>
          <% @users = User.all %>
          <% @users.each do |user| %>
          <div class="timeline-panel">
              <div class="timeline-heading">
                  <!-- Show user name -->
                  <% if user != current_user %>
                  <div class="container blockquote-twitter-tweet card" style="background-color: rgba(255,255,255,0.65); width: 50%; margin-bottom: 2%; border-radius: 6px;">
                      <div class="card-body" style="text-align: center;">
                          <h4><%= link_to user.username , user_show_user_path(user), style: "font-size: 16px;" %>
                          <div class="row stylerow" style="border-bottom: 1px solid #E5E5E5; width: 111%; margin-left: -5.5%;"></div>
                      </div>
                      <div class="timeline-body">
                        <% if !user.admin? %>
                          <div class="field" style="text-align: center;">
                            <% if user.ban? %>
                              <%= link_to 'Unban', user_ban_path(user), method: :put, data: { confirm: 'This user will be unbanned. Proceed?' }, style: "color: black;" %>
                              <% else %>
                                <%= link_to 'Ban', user_ban_path(user), method: :put, data: { confirm: 'This user will be banned. Proceed?' }, style: "color: black;" %>
                              <% end %>
                            <% end %>
                            </div>

                            <div class="field" style="text-align: center">
                            <% if user.mod? %>
                              <%= link_to 'Unmod', user_mod_path(user), method: :put, data: { confirm: 'This user will be unmoded. Proceed?' }, style: "color: black;" %>
                              <% else %>
                                <%= link_to 'Mod', user_mod_path(user), method: :put, data: { confirm: 'This user will be moded. Proceed?' }, style: "color: black;" %>
                              <% end %>
                            <% end %>
                            </div>

                        <% if current_user.admin? %>
                          <div class="field" style="text-align: center">
                            <% if user.admin? %>
                              <% else %>
                                <%= link_to 'Admin', user_admin_path(user), method: :put, data: { confirm: 'This user will be moded. Proceed?' }, style: "color: black;" %>
                              <% end %>
                            <% end %>
                          </div>

                        <% if (current_user.admin? || current_user.mod )&& !current_user?(user) && !user.admin%>
                          <div class="field" style="text-align: center; margin-bottom: 2%;">
                            <%= link_to "Delete", user, method: :delete, data: { confirm: "This user will be deleted. Proceed?" }, style: "color: black;" %>
                          </div>
                        <% else %>
                      </div>
                      <% end %>
                  </div>
                  <% end %>
              </div>
          </div>
        <% end %>
    </div>
</div>

Songify/Songify/app/views/users/show.html.erb
<div class="container message">
  <% if current_user.email == nil %>
    <p style="color: white;">Since you have logged in with twitter you have to <%= link_to "Update your e-mail", edit_user_registration_path %> to comment or review concerts. </p>
    <br/>
  <%end%>
  <h3 style="color: gray;">Welcome to Songify's profile</h3>
  <p style="color: gray;">show your informations <%= current_user.username%></p>
  <br/>
</div>

<div class="container">
    <div class="card cardpr" style="background-color: rgba(255,255,255,0.65); margin-bottom: 10%">
        <div class="row stylerow" style="border-bottom: 1px solid #E5E5E5; width: 100%; margin-left: 0%;">
            <div class="col-sm-2 col-md-2" style="margin-left: 4%;">
                <% if current_user.provider == "twitter" %>
                <img style="width: 90%; height: 55%; margin-top: 30%; color: black;" src="<%= current_user.profile_image_url %>" alt="No Image" class="img-raised rounded-circle img-fluid">
                <%else%>
                <img style="width: 90%; height: 55%; margin-top: 30%; color: black;" src="<%= current_user.avatar.url %>" alt="No Image" class="img-raised rounded-circle img-fluid">
                <%end%>
                <br/>
            </div>
            <div class="col-sm-4 col-md-4" style="color: black;">
                <blockquote>
                    <p><%= current_user.first_name%></p> <small><cite> <%= current_user.location%>, Italy <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                </blockquote>
                <p> Email: <%= current_user.email %>
                    <br/> Username: <%= current_user.username %>
                    <br/> Date of birth: <%= current_user.date_of_birth %>
                    <br/> User id:<% if current_user.provider != "twitter" %> <%= current_user.id %> <%else%> <%=current_user.uid%><%end%>
                    <br/> Gender: <%= current_user.gender %>
                    <br/> Bio: <%=current_user.bio %>
                    <br/><br/> <%= link_to "Edit your account", edit_user_registration_path %>
                </p>
            </div>
        </div>
        <div style="margin-left: 4%; margin-bottom: 1%; margin-top: -2%">

          <h4><% if current_user.favorites != nil && current_user.favorites.split(' ') != nil && current_user.favorites != ' ' %>
                <%= link_to "Favorite music events" ,concert_index2_path(concert_id: current_user.favorites), style: "color: black;" %>
            <% else %>
                <%= link_to "Add some events to your favorites!" , concerts_path(concert_id: current_user.favorites), style: "color: black;" %>
            <% end %>
            </h4>
        </div>
    </div>
</div>

Songify/Songify/app/views/users/show_user.html.erb
<div class="container message">
  <h3 style="color: gray;">Welcome to Songify's profile</h3>
  <p style="color: gray;">show your informations <%= @user.username%></p>
  <br/>
</div>

<div class="container">
    <div class="card cardpr" style="background-color: rgba(255,255,255,0.65); margin-bottom: 18.1%;">
        <div class="row stylerow" style="border-bottom: 1px solid #E5E5E5; width: 100%; margin-left: 0%;">
            <div class="col-sm-2 col-md-2" style="margin-left: 4%;">
                <% if @user.provider == "twitter" %>
                <img style="width: 90%; height: 55%; margin-top: 30%; color: black;" src="<%= @user.profile_image_url %>" alt="No Image" class="img-raised rounded-circle img-fluid">
                <%else%>
                <img style="width: 90%; height: 55%; margin-top: 30%; color: black;" src="<%= @user.avatar.url %>" alt="No Image" class="img-raised rounded-circle img-fluid">
                <%end%>
                <br/>
            </div>
            <div class="col-sm-4 col-md-4" style="color: black;">
                <blockquote>
                    <p><%= @user.first_name%></p> <small><cite> <%= @user.location%>, Italy <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                </blockquote>
                <p> Email: <%= @user.email %>
                    <br/> Username: <%= @user.username %>
                    <br/> Date of birth: <%= @user.date_of_birth %>
                    <br/> User id:<% if @user.provider != "twitter" %> <%= @user.id %> <%else%> <%=@user.uid%><%end%>
                    <br/> Gender: <%= @user.gender %>
                    <br/> Bio: <%= @user.bio %>

                    <%if current_user.id == @user.username %>
                    <%= link_to "Edit your account", edit_user_registration_path %>
                    <%end%>
                </p>
            </div>
        </div>
        <div style="margin-left: 4%; margin-bottom: 1%; margin-top: -2%">
          <h4 style="color: black"><% if @user.favorites != nil && @user.favorites.split(' ') != nil && @user.favorites != ' ' %>
                <%= link_to "Favorite music events" ,concert_index2_path(concert_id: @user.favorites), style: "color: black;" %>
            <% else %>
                No favorites.
            <% end %></h4>
        </div>
    </div>
</div>